
services:
  postgres:
    image: postgres:15-alpine
    container_name: commerce_postgres

    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: commerce_core

    ports:
      - "5435:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: